name: Build 3DS CIA

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile Code
        run: |
          make

      - name: Convert 3DSX to CIA
        run: |
          3DSX_FILE=$(find . -name "*.3dsx" | head -n 1)
          3dsxtool "$3DSX_FILE" output.elf
          
          cat << 'EOF' > build.rsf
          BasicInfo:
            Title                   : "Fruit Ninja 3DS"
            CompanyCode             : "00"
            ProductCode             : "CTR-P-FRUT"
            ContentType             : Application
            Logo                    : Nintendo

          TitleInfo:
            UniqueId                : 0xF2812
            Category                : Application

          Option:
            UseOn3DS                : true

          AccessControlInfo:
            CoreVersion             : 2
            IdealProcessor          : 0
            AffinityMask            : 1
            SystemMode              : 64MB
            StorageId               : Host
            DisableDebug            : true
            EnableFinished          : true
            CanWriteSharedPage      : false
            CanUsePrivilegedPriority: false
            CanAddressAccess        : false
            RunnableOnSleep         : false
            SpecialMemory           : false

            MemoryType              : Application
            HandleTableSize         : 0x200
            IORegisterMapping:
            MemoryMapping:

          SystemControlInfo:
            SaveDataSize            : 0KB
            RemasterVersion         : 0
            StackSize               : 0x00040000
          EOF

          makerom -f cia -o fruitninja3ds.cia -rsf build.rsf -target t -elf output.elf

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FruitNinja-3DS-Build
          path: |
            *.cia
            *.3dsx
