name: Build 3DS CIA

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile 3DSX
        run: |
          make

      - name: Convert 3DSX to CIA
        run: |
          python3 -m pip install 3dsx2cia --break-system-packages
          3dsx2cia *.3dsx fruitninja3ds.cia

      - name: Upload CIA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: FruitNinja-CIA-Build
          path: |
            *.cia
            *.3dsx
